agua_hmo/agua_hmo/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('website.urls'))
]

agua_hmo/website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('manage_users', views.manage_users, name="manage_users"),
    path('manage_payment_concept', views.manage_payment_concept, name="manage_payment_concept"),
    path('create_user/', views.create_user, name="create_user"),
    path('show_user/', views.show_user, name="show_user"),
    path('update-user/', views.update_user, name="update_user"),
    path('delete-user/', views.delete_user, name="delete_user"),
]

agua_hmo/website/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

""" Everytime we made changes to the models, we need to update it. Use the next commands (In order):
    'python manage.py makemigrations'
    'python manage.py migrate'                                                                      """

MAX_CHAR_LENGTH = 20


# Create your models here.

CONTRACT_TYPES = (
        ('Residencial', 'RESIDENCIAL'),
        ('Comercial', 'COMERCIAL'),
        ('Industrial', 'INDUSTRIAL'),
    )

class Users(models.Model):
    meter_number = models.IntegerField(validators=[
            MinValueValidator(10000, "El número debe ser mayor o igual a 10000."),
            MaxValueValidator(99999, "El número debe ser menor o igual a 99999.")
        ], unique=True)
    user_name = models.CharField(max_length=MAX_CHAR_LENGTH)
    home_direction = models.CharField(max_length=MAX_CHAR_LENGTH)
    contract_type = models.CharField(max_length=12, choices=CONTRACT_TYPES)
    register_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.meter_number) + ' : ' + self.user_name

class Concepts(models.Model):
    year = models.DecimalField(max_digits=4, decimal_places=0)
    consumption_per_cubic = models.FloatField()
    drainage_fee = models.FloatField()
    sanitation = models.FloatField()
    red_cross = models.FloatField()
    firefighters = models.FloatField()
    contract_type = models.CharField(max_length=12, choices=CONTRACT_TYPES)
    
    def __str__(self):
        return str(self.year) + ' : ' +self.contract_type

class Debts(models.Model):
    meter_number = models.IntegerField(validators=[
        MinValueValidator(10000, "El número debe ser mayor o igual a 10000."),
        MaxValueValidator(99999, "El número debe ser menor o igual a 99999.")
    ])

    year = models.PositiveSmallIntegerField()
    month = models.PositiveSmallIntegerField()
    cut = models.PositiveSmallIntegerField()
    water_usage_m3 = models.FloatField()
    previous_debt = models.FloatField()
    total_month = models.FloatField()

    def __str__(self):
        return str(self.meter_number) + " : " + str(self.year) + "-" + str(self.month)

agua_hmo/website/forms.py
from django.forms import ModelForm
from .models import Users

class UserForm(ModelForm):
    class Meta:
        model = Users
        fields = '__all__'

agua_hmo/website/views.py
from django.shortcuts import render, redirect
from .models import Users, Debts, Concepts
from .forms import UserForm
from django.utils import timezone
from django.contrib import messages
import random


def home(request):
    return render(request, 'home.html', {})

def manage_users(request):
    return render(request, 'manage_users.html', {})

def manage_payment_concept(request):
    if request.method == 'POST':
        action = request.POST.get('action')
        if action == 'find_user':
            user_meter_number = int(request.POST.get('meter_number', 0))
            searched_user = Users.objects.filter(meter_number=user_meter_number)
            if searched_user.exists():
                return render(request, 'user_manage_payment_concept.html', {'user' : searched_user.first, 'debts' : Debts.objects.filter(meter_number=user_meter_number)})
            else:
                return render(request, 'manage_payment_concept.html', {'error': True})
        if action == 'create_ticket':
            user_meter_number = int(request.POST.get('meter_number', 0))
            ticket_year = int(request.POST.get('year', 0))
            ticket_month = int(request.POST.get('month', 0))
            debt_info = Debts.objects.filter(meter_number=user_meter_number, year=ticket_year, month=ticket_month)
            if debt_info.exists():
                concep_info = Concepts.objects.get(year=ticket_year, contract_type=Users.objects.get(meter_number=user_meter_number).contract_type)
                debt_info = Debts.objects.get(meter_number=user_meter_number, year=ticket_year, month=ticket_month)
                water_cost = concep_info.consumption_per_cubic * debt_info.water_usage_m3
                drainage_cost = concep_info.drainage_fee * water_cost
                sanitation_cost = concep_info.sanitation * water_cost
                red_cross_cost = concep_info.red_cross * water_cost
                firefighters_cost = concep_info.firefighters * water_cost
                total_month = water_cost + drainage_cost + sanitation_cost + red_cross_cost + firefighters_cost
                previous_debt = debt_info.previous_debt
                total = total_month + previous_debt

                return render(request, 'ticket.html', {'user' : Users.objects.filter(meter_number=user_meter_number).first,
                                                    'ticket' : Debts.objects.filter(meter_number=user_meter_number, year=ticket_year, month=ticket_month).first,
                                                    'water_cons' : water_cost,
                                                    'drainage' : drainage_cost,
                                                    'sanitation' : sanitation_cost,
                                                    'red_cross' : red_cross_cost,
                                                    'firefighters' : firefighters_cost,
                                                    'total_month' : total_month,
                                                    'previous_debt' : previous_debt,
                                                    'total' : total
                                                    })
            else:
                return render(request, 'user_manage_payment_concept.html', {'debt_error' : False, 'ticket_error' : True,
                                                                            'user' : Users.objects.filter(meter_number=user_meter_number).first, 'debts' : Debts.objects.filter(meter_number=user_meter_number)})


        if action == 'delete_debts':
            user_meter_number = int(request.POST.get('meter_number', 0))
            searched_user = Users.objects.filter(meter_number=user_meter_number)
            user_history_of_debts = Debts.objects.filter(meter_number=user_meter_number)
            if user_history_of_debts.exists():
                user_history_of_debts.delete()
            return render(request, 'user_manage_payment_concept.html', {'debt_error' : False, 'ticket_error' : False,
                                                                            'user' : searched_user.first, 'debts' : Debts.objects.filter(meter_number=user_meter_number)})

        if action == 'create_debt':
            user_meter_number = int(request.POST.get('meter_number', 0))
            searched_user = Users.objects.filter(meter_number=user_meter_number)
            user_history_of_debts = Debts.objects.filter(meter_number=user_meter_number)
            if user_history_of_debts.exists():
                user_last_debt = user_history_of_debts.latest('id')
                
                random_water_usage = random.uniform(1, 10)
                # Function to calculate the next year/month of the new debt
                def calculate_next_debt_date(year, month):
                    new_month = month + 1
                    if(new_month >= 13) : 
                        return(year+1, 1)
                    else:
                        return(year, new_month)
                new_debt_date = calculate_next_debt_date(user_last_debt.year, user_last_debt.month)
                if not(Concepts.objects.filter(year=new_debt_date[0], contract_type=Users.objects.get(meter_number=user_meter_number).contract_type).exists()):
                    return render(request, 'user_manage_payment_concept.html', {'debt_error' : True, 'ticket_error' : False,
                                                                            'user' : Users.objects.filter(meter_number=user_meter_number).first, 'debts' : Debts.objects.filter(meter_number=user_meter_number)})
                concep_info = Concepts.objects.get(year=new_debt_date[0], contract_type=Users.objects.get(meter_number=user_meter_number).contract_type)
                water_cost = concep_info.consumption_per_cubic * random_water_usage
                total_month_full = (water_cost +
                                         concep_info.drainage_fee * water_cost + 
                                         concep_info.sanitation * water_cost +
                                         concep_info.red_cross * water_cost +
                                         concep_info.firefighters * water_cost +
                                         user_last_debt.total_month)
                # Generar pagina para cargar nuevo adeudeo.
                new_debt = Debts(meter_number = user_meter_number,
                                 year = new_debt_date[0],
                                 month = new_debt_date[1],
                                 cut = 20,
                                 water_usage_m3 = round(random_water_usage, 3),
                                 previous_debt = user_last_debt.total_month,
                                 total_month = total_month_full)
                new_debt.save()
                return render(request, 'user_manage_payment_concept.html', {'user' : searched_user.first, 'debts' : Debts.objects.filter(meter_number=user_meter_number)})
            else:
                current_date = timezone.now().date()
                current_year = current_date.year
                current_month = current_date.month

                concep_info = Concepts.objects.get(year=current_year, contract_type=Users.objects.get(meter_number=user_meter_number).contract_type)
                random_water_usage = random.uniform(1, 10)
                water_cost = concep_info.consumption_per_cubic * random_water_usage
                
                total_month_full = (water_cost +
                                         concep_info.drainage_fee * water_cost + 
                                         concep_info.sanitation * water_cost +
                                         concep_info.red_cross * water_cost +
                                         concep_info.firefighters * water_cost)
                                        
                # Generar pagina para cargar un nuevo adeudo inicial.
                new_debt = Debts(meter_number = user_meter_number,
                                 year = current_year,
                                 month = current_month,
                                 cut = 20,
                                 water_usage_m3 = round(random_water_usage, 3),
                                 previous_debt = 0,
                                 total_month = total_month_full)
                new_debt.save()
                return render(request, 'user_manage_payment_concept.html', {'user' : searched_user.first, 'debts' : Debts.objects.filter(meter_number=user_meter_number)})

    return render(request, 'manage_payment_concept.html', {'error': False})

def create_user(request):
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Usuario creado con exito')
        else:
            messages.error(request, 'Numero de medidor ya existe.')
    context = {'form': form}
    return render(request, 'user_form.html', context)

def delete_user(request):
    if request.method == 'POST':
        user_meter_number = int(request.POST.get('meter_number', 0))
        searched_user = Users.objects.filter(meter_number=user_meter_number)
        if searched_user.exists():
            searched_user.delete()
            return render(request, 'delete.html', {'error': False, 'succes' : True})
        else:
            messages.error(request, 'Numero de medidor no existe.')
    return render(request, 'delete.html', {'error': False})

def update_user(request):
    if request.method == 'POST':
        user_meter_number = int(request.POST.get('meter_number', 0))
        searched_user = Users.objects.filter(meter_number=user_meter_number)
        if searched_user.exists():
            user_user_name = request.POST.get('user_name', 0)
            user_contract_type = request.POST.get('contract_type', 0)
            user_home_direction = request.POST.get('home_direction', 0)

agua_hmo/website/templates/delete.html
<!DOCTYPE html>
<html lang="es">

    <style>

        h1{
            display: absolute;
            font-size: 1cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            justify-content: center;
            margin-left: 1cm;
        }

        button{
            font-size: .5cm;
            margin-top: 0.5cm;
            margin-left: 0.4cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }

        input{
            font-size: .5cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }


    </style>



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion de pagos</title>
</head>
<body>

    <form action="http://127.0.0.1:8000/manage_users">
        <button type="submit"> Volver </button>
    </form>

    <h1>Ingresa el numero de medidor a eliminar:</h1>
    <form method="post">
        {% csrf_token %}
        <input type="number" name="meter_number" required>
        <button type="submit" name="action" value="find_user">Eliminar</button>
    </form>

	{% if messages %}
		<div class="messages" style="color: red;">
		{% for message in messages %}
			<div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
				{{ message }}
			</div>
		{% endfor %}
		</div>
	{% endif %}

    {% if succes %}
    <div style="color: green;">
        Usuario eliminado con exito.
    </div>
    {% endif %}
</body>
</html>

agua_hmo/website/templates/home.html
{% load static %}

<!doctype html>
    <title>Sistema de agua</title>
    
    <style>
        h1{
            display: absolute;
            font-size: 1cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            justify-content: center;
            margin-left: 0.3cm;
        }
        a{
            font-size: 0.5cm;
            display: flex;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            margin-left: 0.5cm;
            margin-bottom: 0.5cm;
            color: black;
        }
    </style>
    
    <h1> SISTEMA DE AGUA </h1>
    <a href="{% url 'manage_users' %}"> - Gestionar Usuarios</a>
    <a href="{% url 'manage_payment_concept' %}"> - Gestionar Pagos</a>
</html>

agua_hmo/website/templates/manage_payment_concept.html
<!DOCTYPE html>
<html lang="es">

    <style>

        h1{
            display: absolute;
            font-size: 1cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            justify-content: center;
            margin-left: 1cm;
        }

        button{
            font-size: .5cm;
            margin-top: 0.5cm;
            margin-left: 0.4cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;  
        }

        input{
            font-size: .5cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }


    </style>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion de pagos</title>
</head>
<body>

    <form action="http://127.0.0.1:8000/manage_users">
        <button type="submit"> Volver </button>
    </form>

    <h1>Ingresa el numero de su medidor:</h1>
    <form method="post">
        {% csrf_token %}
        <input type="number" name="meter_number" required>
        <button type="submit" name="action" value="find_user">Buscar</button>
    </form>

    {% if error %}
    <div style="color: red;">
        El número ingresado no es válido.
    </div>
    {% endif %}
</body>
</html>

agua_hmo/website/templates/manage_users.html
<style>

    button{
            font-size: .5cm;
            margin-top: 0.5cm;
            margin-left: 0.8cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    
    h1{
        display: absolute;
            font-size: 1cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            justify-content: center;
            margin: 1cm;
    }

    a{
        font-size: 0.5cm;
            display: flex;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            margin-left: 0.5cm;
            color: black;
    }
    
</style>

<form action="http://127.0.0.1:8000">
        <button type="submit"> Volver </button>
    </form>

<h1> USUARIOS </h1>

<a href="{% url 'create_user' %}">Crear usuario </a>
<br>
<br>

<a href="{% url 'delete_user' %}">Eliminar usuario </a>
<br>
<br>

<a href="{% url 'update_user' %}">Modificar usuario </a>
<br>
<br>

<a href="{% url 'show_user' %}">Buscar usuario </a>
<br>

agua_hmo/website/templates/search.html
<!DOCTYPE html>
<html lang="es">

    <style>

        h1{
            display: absolute;
            font-size: 1cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            justify-content: center;
            margin-left: 1cm;
        }

        button{
            font-size: .5cm;
            margin-top: 0.5cm;
            margin-left: 0.4cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }

        input{
            font-size: .5cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }


    </style>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion de pagos</title>
</head>
<body>

    <form action="http://127.0.0.1:8000/manage_users">
        <button type="submit"> Volver </button>
    </form>

    <h1>Ingresa el numero de medidor a buscar:</h1>
    <form method="post">
        {% csrf_token %}
        <input type="number" name="meter_number" required>
        <button type="submit" name="action" value="find_user">Buscar</button>
    </form>

    {% if error %}
    <div style="color: red;">
        El número ingresado no existe.
    </div>
    {% endif %}
</body>
</html>

agua_hmo/website/templates/ticket.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Recibo de pago</title>
        <style>
            body{
                display: absolute;
                font-size: 4.2ch;
                font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
                justify-content: center;
    
            }
    
            .usuario,
            .usage,
            .charge{
                font-size: 0.5cm;
                justify-content:left;
                position: flex;
                font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            }
    
            p{
                font-size: 0.6cm;
            }

        button{
            font-size: .5cm;
            margin-top: 0.5cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }
    
        </style>
    </head>

    <form action="http://127.0.0.1:8000">
        <button type="submit"> Volver </button>
    </form>

<body>
    <h1>AVISO DE PAGO</h1>

    <p>|----------DATOS DEL CLIENTE---------|</p>

    <p class="usuario">
        NOMBRE DE USUARIO: {{ user.user_name }} <br>
        DIRECCION: {{ user.home_direction }} <br>
        TARIFA: {{ user.contract_type }} <br>
        MEDIDOR: {{ user.meter_number }} <br>
    </p>

    <p>|--------DATOS DEL CONSUMO--------|</p>

    <p class="usage">
        MES FACTURADO:&emsp; {{ ticket.month }} <br>
        CORTE A PARTIR DE:&emsp; {{ ticket.cut }} <br>
        CONSUMO METROS CUB:&emsp; {{ ticket.water_usage_m3 }} <br>
        FACTURADO METROS CUB:&emsp; {{ ticket.water_usage_m3 }} <br>
    </p>

    <p>|--------CONCEPTOS DE COBRO--------|</p>

    <p class="charge">
        CONSUMO AGUA: &emsp;          {{ water_cons }}<br>
        CUOTA DE DRENAJE:&emsp;       {{ drainage }}<br>
        SANEAMIENTO:&emsp;            {{ sanitation }}<BR>
        APORTACION CRUZ ROJA:&emsp;   {{ red_cross }}<br>
        APORTACION BOMBEROS:&emsp;    {{ firefighters }}<br>
        <br>
        TOTAL DEL MES:&emsp; {{total_month}}<br>
        ADEUDO ANTERIOR:&emsp;  {{previous_debt}}<br>
        TOTAL A PAGAR:&emsp; {{total}}<br>
    </p>

    <button>Pagar</button>
</body>
</html>

agua_hmo/website/templates/update_user.html
<!DOCTYPE html>
<html lang="en">

    <style>

        h1{
            display: absolute;
            font-size: 1cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            justify-content: center;
            margin-left: 1cm;
        }

        button{
            font-size: .5cm;
            margin-top: 0cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }

        form{
            font-size: 0.5cm;
            display: absolute;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            margin-left: 0.5cm;
            margin-top: 1cm;
            color: black;
        }

        input{
            margin: 0.2cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }

    </style>

<head>
    <meta charset="UTF-8">
    <title>Actualizar usuario</title>
</head>
<body>

    <form action="http://127.0.0.1:8000/manage_users">
        <button type="submit"> Volver </button>
    </form>

<h1> Actualizar usuario </h1>
<div>
    <form method="post">
        {% csrf_token %}
        Numero de medidor (existente): <input type="number" name="meter_number" required> <br>
        Nombre: <input type="text" name="user_name" required> <br>
        Direccion: <input type="text" name="home_direction" required> <br>
        <label for="id_contract_type">
        Contract type: </label> <select name="contract_type" required id="id_contract_type">
        <option value="" selected>---------</option>

  <option value="Residencial">Residencial</option>

  <option value="Comercial">Comercial</option>

  <option value="Industrial">Industrial</option>

                    <br><input type="Submit" value="Actualizar"/>

    </form>
</div>

{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert" style="color: {% if message.tags == 'error' %}red{% elif message.tags == 'success' %}green{% endif %};">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}
    

</body>
</html>

agua_hmo/website/templates/user_form.html
<!DOCTYPE html>
<html lang="en">

    <style>

        button{
            font-size: .5cm;
            margin-top: 0.5cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }

        h1{
            display: absolute;
            font-size: 1cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            justify-content: center;
            margin-left: 1cm;
        }

        body,
        form{
            font-size: 0.5cm;
            display: absolute;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            margin-left: 0.5cm;
            margin-bottom: 1cm;
            color: black;
        }

        input{
            margin-bottom: 0.5cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }

    </style>

<head>
    <meta charset="UTF-8">
    <title>Crear usuario</title>
</head>

<body>

    <form action="http://127.0.0.1:8000/manage_users">
        <button type="submit"> Volver </button>
    </form>

    <h1>Crear usuario</h1>

    <div>
        <form method="POST" action="">
            {% csrf_token %}
            Numero de medidor: {{ form.meter_number }}
            <br>
            Nombre de usuario: {{ form.user_name }}
            <br>
            Direccion: {{ form.home_direction }}
            <br>
            Tipo de contrato: {{ form.contract_type }}
            <br>
            <input type="Submit" value="Crear usuario"/>
        </form>
    </div>
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert" style="color: {% if message.tags == 'error' %}red{% elif message.tags == 'success' %}green{% endif %};">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}
</body>
</html>

agua_hmo/website/templates/user_info.html
<!DOCTYPE html>
<html lang="en">

    <style>

        h1{
            display: absolute;
            font-size: 1cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            justify-content: center;
            margin-left: 1cm;
        }

        p{
            font-size: 0.7cm;
            display: flex;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            margin-left: 0.5cm;
            color: black;
        }

        button{
            font-size: .5cm;
            margin-top: 0.5cm;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
        }


    </style>

<head>
    <meta charset="UTF-8">
    <title>Informacion del usuario</title>
</head>
<body>

    <form action="http://127.0.0.1:8000/manage_users">
        <button type="submit"> Volver </button>
    </form>

    <h1> Informacion del usuario</h1>
    <p>Usuario: {{ user.user_name}}</p>
    <p>Medidor: {{ user.meter_number}}</p>
    <p>Tipo de contrato: {{ user.contract_type}}</p>
    <p>Direccion: {{ user.home_direction}}</p>
    <p>Fecha de alta: {{ user.register_date}}</p>

</body>
</html>